### PR TITLE
Feature/ia-user-auth

### LINKED ISSUE #15: As a user, I want to be able to register on this platform
**__User Story Description__**
As a user
I want to register on this platform by creating a username and password
So that I can save my preferences and information

**__Steps to Follow (optional)__**
- [ ] Create user model
- [ ] Create register user schema
- [ ] Configure user router
- [ ] Register user resolver
- [ ] Additional steps as necessary

**__Additional Considerations__**
https://next-auth.js.org/

### LINKED ISSUE #22: As a registered user, I want to be able to login on this platform
**__User Story Description__**
As a registered user
I want to log in with my username and password
So I can access my account information

**__Steps to Follow (optional)__**
- [ ] Add login token to prisma
- [ ] Login schema
- [ ] Login resolver
- [ ] Verify Login resolver
- [ ] Additional steps as necessary

**__Additional Considerations__**
https://next-auth.js.org/

### LINKED ISSUE #23: User Authentication
**__Feature Description__**
The user will need to be added to the database so the system can track the user's activities, power usage, gas usage, flights, and miles/km driven. So an authentication process will need to be added and a login process so an authenticated user can come back to the website and view their saved information. This epic includes user stories for the frontend and backend tickets necessary to get user authentication working.

**__Major User Stories/tasks__**
- [ ] User Story #15 
- [ ] User Story #39 
- [ ] User Story #22
- [ ] User Story #40 

**__Additional Considerations__**
NextAuth docs - https://next-auth.js.org/getting-started/rest-api

### LINKED ISSUE #39: As a user, I want to be able to register on this platform
**__User Story Description__**
As a user
I want to register on this platform by creating a username and password
So that I can save my preferences and information

**__Steps to Follow (optional)__**
- [ ] Create form on '/register' page
- [ ] Form on submit must send correct data to backend
- [ ] Should reroute the user to another page if they're already logged in or after successful submission
- [ ] Additional steps as necessary

**__Additional Considerations__**
Keep in mind the backend version of this ticket #15

### LINKED ISSUE #40: As a registered user, I want to be able to login on this platform
**__User Story Description__**
As a registered user
I want to log in with my username and password
So I can access my account information

**__Steps to Follow (optional)__**
- [ ] Create form on '/login' page
- [ ] Form on submit must send correct data on backend
- [ ] Should reroute the user to another page if they're already logged in or after successful submission
- [ ] Additional steps as necessary

**__Additional Considerations__**
Keep in mind the backend version of this ticket #22

### PR DESCRIPTION
**Pull request by ialej001**
User authentication

- Implemented full stack login & 1-click registration
- New users will get routed immediately to account preferences to set their country and state (not complete)
- Existing users will be routed to account dashboard
- Four different authentication providers: Google, Facebook, GitHub, and Email One Time Password (email login token)

**Installs one new package and the env file will need to be updated.**

Closes tickets: #15, #22, #23, #39, #40

### CODE REVIEW

**Review by victoriacheng15 — APPROVED** [review]
Looks good. Can login and out with the local environment. 👍

**Comment by TiciaD** [comment]
If I login then logout and try to login with the same email am I supposed to get the verification link? Does that send every time someone re-logs in? Not saying it's wrong just want to know if that's the intended functionality

**Comment by ialej001** [comment]
> If I login then logout and try to login with the same email am I supposed to get the verification link? Does that send every time someone re-logs in? Not saying it's wrong just want to know if that's the intended functionality

If I'm understanding correctly, it should email you each time you attempt to log in via email. The email serves as your password. It's how next-auth works in this regard and it's tied to the session. By logging out, that session is invalidated and you'll need to obtain a new token to get a new session.

Is that the behavior you were seeing?

**Comment by TiciaD** [comment]
> > If I login then logout and try to login with the same email am I supposed to get the verification link? Does that send every time someone re-logs in? Not saying it's wrong just want to know if that's the intended functionality
> 
> If I'm understanding correctly, it should email you each time you attempt to log in via email. The email serves as your password. It's how next-auth works in this regard and it's tied to the session. By logging out, that session is invalidated and you'll need to obtain a new token to get a new session.
> 
> Is that the behavior you were seeing?

Yep just wanted to make sure that's what we were expecting, in that case approved!

**Review by TiciaD — APPROVED** [review]

**Pull request merged**
