### PR TITLE
Component/cta

### LINKED ISSUE #57: CTA card component
**__Task Description__**
Create CTA card component that takes in an icon, description, and link as props
Card should be clickable and take user to link given in props
Optionally can take in color as prop depending on how many colors all the cards utilize in wireframe
Styling should match mockup

Screenshot 2022-08-18 143353

**__Technical Considerations__**
Try to utilize Flowbite Component Library if possible:
https://flowbite-react.com/card

**__Additional Considerations__**
[Mockup reference](https://www.figma.com/file/5kGltcw2FvojrkSf9PaMKu/MyCarbonFootprint?node-id=0%3A1)

### PR DESCRIPTION
**Pull request by ptrbtlr**
- CTA Cards and Card Component Complete

**NOTE**
Minor CSS bug on the first card on desktop for some reason. Will need to look into that!

### CODE REVIEW

**Review by victoriacheng15 — COMMENTED** [review]
I believe the shipping is under `nice_to_have` label, so I think we may not need the shipping card at this moment. Otherwise, it looks good

**Comment by ptrbtlr** [comment]
> I believe the shipping is under `nice_to_have` label, so I think we may not need the shipping card at this moment. Otherwise, it looks good

Oh yeah, I was just going by the Figma file. Can be easily removed if we don't need it! Thanks :)

**Comment by victoriacheng15** [comment]
> > I believe the shipping is under `nice_to_have` label, so I think we may not need the shipping card at this moment. Otherwise, it looks good
> 
> Oh yeah, I was just going by the Figma file. Can be easily removed if we don't need it! Thanks :)

Ah I see. I will approve this shortly then. 😄

**Review by victoriacheng15 — APPROVED** [review]

**Review by TiciaD — CHANGES_REQUESTED** [review]
Looks good Cian, we probably should remove the shipping card though since there is no endpoint for it so it'll just send the user to 404 response page

**Review by amandaalexandre — DISMISSED** [review]
- As per clean code convention, create a separate file for the Cards info (optional);
- Images that are dynamically rendered need to be put under the puclib fodler or won't show in production mode.

**Review by TiciaD — APPROVED** [review]

**Review by ialej001 — APPROVED** [review]
Undid unnecessary branch merges. Added in a missing import. Cards are responsive and point to the appropriate pages. Good job Cian

**Pull request merged**
