### PR TITLE
Feature/vc navigation routes

### LINKED ISSUE #29: As a user, I would like to navigate to other pages on the website
**__User Story Description__**
As a user
I want to navigate to other pages on the website
So I can see what else the website has to offer

**__Steps to Follow (optional)__**
- [ ] Organize routing with Next.js
- [ ] Additional steps as necessary

**__Additional Considerations__**
https://nextjs.org/docs/routing/introduction

**Example Page Structure**
Home ('/')
  - Electricity Consumption Page ('/electricity')
  - Fuel Consumption Page ('/fuel')
  - Travel Page ('/travel')
  - Login Page ('/login')
  - SignUp Page ('/register')
  - Account ('/account')
    - Emission Reports History ('/reports') or ('/history')
      - Report Details ('/:reportid')

### PR DESCRIPTION
**Pull request by victoriacheng15**
Added 
- pages for electricity consumption, fuel consumption, travel, login, and register
- account folder contains account and emission-reports pages for registered users
- nav links to the 4 pages from first list

for #29

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@ialej001, yes I added nav links, so we could go to certain page and then back to home if needed. 

Also, I believe the branch is pushed to remote. I think you may need to type out the name of the branch fully or almost fully. 

(To answer your questions from the PR that I closed)

**Review by ialej001 — DISMISSED** [review]
package.json isn't updated to development: specifically the `npm run dev` script isn't using the concurrently command string to run the mock API in conjuction with Next.

This might be just me being a noob when it comes to git, but that shouldn't be a problem right?

**Comment by victoriacheng15** [comment]
> package.json isn't updated to development: specifically the `npm run dev` script isn't using the concurrently command string to run the mock API in conjuction with Next.
> 
> This might be just me being a noob when it comes to git, but that shouldn't be a problem right?

Umm, I believe GitHub would have informed us that there is a merge conflict before hit the merge pull request button, and then we will have to resolve it somehow as usual. I don't think we can find out until 2 approvals.

**Review by TiciaD — CHANGES_REQUESTED** [review]
This looks great Victoria, thanks for setting up all of the pages! The only issue I'm finding is with the account page. I should see the Account page by going to `http://localhost:3000/account/` but instead I have to go to `http://localhost:3000/account/account`. 

The router will automatically route files named index to the root of the directory so instead of account.tsx in the account folder it should be index.tsx so it knows it's a root directory. Hopefully that makes sense!

**Comment by TiciaD** [comment]
> > package.json isn't updated to development: specifically the `npm run dev` script isn't using the concurrently command string to run the mock API in conjuction with Next.
> > This might be just me being a noob when it comes to git, but that shouldn't be a problem right?
> 
> Umm, I believe GitHub would have informed us that there is a merge conflict before hit the merge pull request button, and then we will have to resolve it somehow as usual. I don't think we can find out until 2 approvals.



> package.json isn't updated to development: specifically the `npm run dev` script isn't using the concurrently command string to run the mock API in conjuction with Next.
> 
> This might be just me being a noob when it comes to git, but that shouldn't be a problem right?

@victoriacheng15 is your branch based off of main or development? That might be why it's not picking up those changes. I believe Ivan merged those changes to development but main should still be the initial project setup and wouldn't have the same contents as development

**Comment by victoriacheng15** [comment]
@TiciaD I made the change as the requested.

**Comment by TiciaD** [comment]
Sorry @victoriacheng15 I probably wasn't clear in my review, you had it right with the account folder the first time, you only needed to change the name of the `account.tsx` file to `index.tsx`. This way we can have routing that looks like `http://localhost:3000/account/` and `http://localhost:3000/account/emissions-reports`

**Comment by victoriacheng15** [comment]
@TiciaD my bad and I will keep in mind about the `index.tsx` for the future development.

**Comment by TiciaD** [comment]
> @TiciaD my bad and I will keep in mind about the `index.tsx` for the future development.

No worries! Glad you can see the use in using `index.tsx` and leveraging the file structure, it really does make routing much easier!

**Comment by TiciaD** [comment]
Sorry accidentally hit close lol

**Review by TiciaD — APPROVED** [review]

**Review by ialej001 — APPROVED** [review]
good job

**Pull request merged**
