### PR TITLE
Feature/ia tickets 26 71 user dashboard

### LINKED ISSUE #26: As an authenticated user, I want to be able to see a history of my carbon emissions reports
**__User Story Description__**
As a user
I want to be able to see a history of my carbon emissions reports
So I can see how my CO2 costs change over time

**__Steps to Follow (optional)__**
- [x] After clicking on the appropriate tile, render a new page containing a table
- [ ] Each table should provide the complete details of each calculation in a row
- [ ] Provide functionality to filter and sort by date
- [ ] Provide functionality to sort by column (optional)
- [ ] Additional steps as necessary

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

### LINKED ISSUE #71: As a registered user I want to view my dashboard so I can see my carbon emissions history
**__User Story Description__**
As a registered user,
I want to view my dashboard
So I can see my carbon emissions history

**__Steps to Follow (optional)__**
- [x] Create a component for the emissions history table that fetches previous carbon emission reports from the user
- [x] Create a side navbar with routes to the dashboard home page and dashboard preferences page
- [x] If the user isn't logged in `/account` should route to `/login`
- [x] Additional steps as necessary

**__Additional Considerations__**
Rough wireframe for reference (feel free to adjust anything this is just a rough template of what to do)
AccountHomePage

### PR DESCRIPTION
**Pull request by ialej001**
And the last big ticket!

Full featured dashboard with individual summary pages:

Dash:
- Total emissions summary _based on the user's unit preference_
- Circular progress indicators change color based on its respective percentage
  - 0% should be displayed when there is absolute no calculations saved
  - Otherwise, the percentage should be rendered center of the circle
  - Color changes happen at:
    - [ 0-40 ] %: green
    - ( 40-80 ] %: yellow
    - ( 80-100 ] %: red
- Each card also changes its emissions value _based on the user's unit preference_

Fuel, Electricity, and Flight summary pages:
- Render a responsive table, collapsing columns as the view-port shrinks
- Each page has a header
- Each page has a 'empty table' message, linking to the appropriate calculator page to start

Vehicle summary page:
- On larger screens, a tabbed UI is rendered. Each tab corresponds to a user's vehicle
- On smaller screens, an accordion UI is rendered
- In either style:
  - A table is rendered, responsive to the size of the view-port, collapsing columns as needed.
- For each vehicle, if no data exists, a message and link will appear to redirect to the proper calculator

All summary pages:
- All data is sorted recent to oldest, top to bottom.

Let me know if you find problems!

**You need to run `npm i` to get the package I used for the circular progress indicators!**

Closes tickets #26, #71

### CODE REVIEW

**Review by TiciaD — COMMENTED** [review]
This looks amazing Ivan! The only issues I'm having is for mobile responsiveness. I don't know if you want to make a separate cleanup ticket for that or if you think they're easy fixes but here's what I've found:

Cards overlap on Tablet size screens (`768px`)
Screenshot 2022-09-08 181122


On mobile screens (`320px`) the cards are overflowing and getting cut off I think the padding for the cards needs to be smaller when on mobile
Screenshot 2022-09-08 181300

**Comment by ialej001** [comment]
> Cards overlap on Tablet size screens (`768px`)
> 
> On mobile screens (`320px`) the cards are overflowing and getting cut off I think the padding for the cards needs to be smaller when on mobile

Fixed!

**Review by TiciaD — APPROVED** [review]
Thanks for fixing those responsiveness issues! Looks good now, approved!

**Review by amandaalexandre — APPROVED** [review]
Good job! Are we production ready?

**Pull request merged**
