### PR TITLE
Style/footer

### PR DESCRIPTION
**Pull request by amandaalexandre**
Footer overhaul with:

- Responsive background;
- Added links to CHingu and the API;
- Added the team;

### CODE REVIEW

**Comment by TiciaD** [comment]
The styling looks good on mobile but kind of off on larger screens:
Screenshot 2022-09-03 122814

**Comment by TiciaD** [comment]
Also can we maybe add some hover effects to the links? Maybe some underlines or something so it's a little more clear they can be clicked?

Screenshot 2022-09-03 125823

**Comment by amandaalexandre** [comment]
> Also can we maybe add some hover effects to the links? Maybe some underlines or something so it's a little more clear they can be clicked?
> 
> Screenshot 2022-09-03 125823

Done.

**Comment by amandaalexandre** [comment]
> The styling looks good on mobile but kind of off on larger screens: Screenshot 2022-09-03 122814

Fixed it:
image

**Comment by TiciaD** [comment]
> > The styling looks good on mobile but kind of off on larger screens: Screenshot 2022-09-03 122814
> 
> Fixed it: image

So on larger screens the wave won't be visible it'll just be a green background? Is there any way we can get the SVG to scale up appropriately on larger screens or is that the only way? I played around with it and I think if you use a div with relative positioning that has the background-image set to the wave image and a div with absolute positioning that holds the text you may be able to get it to work

**Pull request closed without merging**
